const screen=document.getElementById('screen');
const jobs=[
 {title:'Productiemedewerker',company:'Productiebedrijf',city:'Hoogeveen',type:'Fulltime',tag:'Productie'},
 {title:'Magazijnmedewerker',company:'Logistiek bedrijf',city:'Zwolle',type:'Fulltime',tag:'Logistiek'},
 {title:'Logistiek medewerker',company:'Distributiecentrum',city:'Meppel',type:'Parttime',tag:'Logistiek'},
 {title:'Schoonmaakmedewerker',company:'Schoonmaakbedrijf',city:'Hoogeveen',type:'Parttime',tag:'Schoonmaak'}
];
function layout(x){return `<div class="content">${x}</div>`}
function nav(page){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.s===page))}
function show(page){
 nav(page); let x='';
 if(page==='home') x=`
 <section class="hero"><div class="eyebrow">YANIMDA · Hollanda</div><h1>Merhaba 👋</h1><p class="sub">Yeni bir ülkede günlük hayatını daha kolay hale getirecek araçlar burada.</p><button class="primary" onclick="show('jobs')">İş bulmaya başla&nbsp; →</button></section>
 <div class="section-head"><h2>Hızlı erişim</h2><button onclick="show('profile')">Tümünü gör</button></div>
 <div class="quick-grid">
 <button class="quick-card" onclick="show('jobs')"><span class="icon">💼</span><strong>İş Bul</strong><small>Güncel fırsatları keşfet</small></button>
 <button class="quick-card" onclick="show('learn')"><span class="icon">📖</span><strong>Hollandaca Öğren</strong><small>Gerçek hayattan adım adım</small></button>
 <button class="quick-card" onclick="show('translate')"><span class="icon">🌐</span><strong>Çeviri</strong><small>Türkçe ↔ Nederlands</small></button>
 <button class="quick-card" onclick="show('nearby')"><span class="icon">📍</span><strong>Yakınımda</strong><small>Günlük ihtiyaçlarını bul</small></button>
 </div>
 <div class="section-head"><h2>Bugün yanında</h2></div>
 <button class="feature" onclick="show('learn')"><div class="feature-row"><div class="feature-icon">🇳🇱</div><div><strong>Bugünün Hollandacası</strong><small>“Hoe gaat het?” · Nasılsın?</small></div><span>›</span></div></button>
 <div class="trust"><h2>YANIMDA</h2><p>Yeni bir ülkede yalnız değilsin. Dil, iş ve günlük yaşam için ihtiyacın olan araçları tek yerde bul.</p></div>`;
 if(page==='jobs') x=`<button class="back" onclick="show('home')">← Ana sayfa</button><h1 class="page-title">İş Bul</h1><p class="sub">Hollanda'daki fırsatları keşfet. İlk sürümde yalnızca ilanları gösteriyoruz.</p><div class="search"><span>⌕</span><input placeholder="Pozisyon, sektör veya şehir ara..." oninput="filterJobs(this.value)"></div><div class="filter-row"><button class="filter active">Tümü</button><button class="filter">Fulltime</button><button class="filter">Parttime</button><button class="filter">Hoogeveen</button><button class="filter">Zwolle</button></div><div id="joblist">${jobs.map(jobCard).join('')}</div>`;
 if(page==='learn') x=`<button class="back" onclick="show('home')">← Ana sayfa</button><h1 class="page-title">Hollandaca Öğren 🇳🇱</h1><p class="sub">Kitap dili değil; Hollanda'da gerçekten duyacağın ve kullanacağın Hollandaca.</p><div class="learn-card"><span class="level">A1 · Başlangıç</span><h2>Günlük Konuşmalar</h2><p class="sub">Tanışma, market, ulaşım, iş ve günlük hayat.</p><div class="progress"><span></span></div><div class="lesson-row"><span>İlerleme</span><strong>18%</strong></div></div><div class="lesson"><div class="num">01</div><div><strong>Tanışma & selamlaşma</strong><small>Hoi, hallo, hoe gaat het?</small></div><span>›</span></div><div class="lesson"><div class="num">02</div><div><strong>Markette konuşma</strong><small>Wat kost dit? · Dit is alles.</small></div><span>›</span></div><div class="lesson"><div class="num">03</div><div><strong>İş yerinde Hollandaca</strong><small>Werk, pauze, klaar, wachten.</small></div><span>›</span></div>`;
 if(page==='translate') x=`<button class="back" onclick="show('home')">← Ana sayfa</button><h1 class="page-title">Çeviri</h1><p class="sub">Günlük konuşmalar için hızlı ve sade çeviri.</p><div class="translate-box"><div class="lang-row"><button class="lang active">🇹🇷 Türkçe</button><button class="lang">🇳🇱 Nederlands</button></div><textarea id="translateInput" class="textarea" placeholder="Çevirmek istediğin metni yaz..."></textarea><div class="translate-actions"><button class="ghost" onclick="clearTranslate()">Temizle</button><button class="primary" onclick="demoTranslate()">Çevir →</button></div></div><div id="translateResult"></div>`;
 if(page==='nearby') x=`<button class="back" onclick="show('home')">← Ana sayfa</button><h1 class="page-title">Yakınımda 📍</h1><p class="sub">Günlük hayatında ihtiyaç duyabileceğin yerleri kolayca bul.</p><div class="near-grid">${[['🛒','Market'],['💊','Eczane'],['🏛️','Belediye'],['🚆','Ulaşım'],['🏥','Doktor'],['📚','Kütüphane'],['🏦','Banka'],['📮','Postane']].map(v=>`<button class="near-card" onclick="toast('${v[1]} için konum özelliğini bir sonraki aşamada bağlayacağız.')"><span>${v[0]}</span><strong>${v[1]}</strong><small>Yakındaki yerleri bul</small></button>`).join('')}</div>`;
 if(page==='profile') x=`<button class="back" onclick="show('home')">← Ana sayfa</button><h1 class="page-title">Profil & Ayarlar</h1><p class="sub">YANIMDA'yı kendine göre düzenle.</p><div class="profile-card"><div class="profile-row"><div><strong>Dil</strong><small>Türkçe</small></div><span>›</span></div><div class="profile-row"><div><strong>Bildirimler</strong><small>Önemli güncellemeler</small></div><div class="switch"></div></div><div class="profile-row"><div><strong>Gizlilik</strong><small>Gereksiz kişisel belge istemiyoruz.</small></div><span>›</span></div></div><div class="feature"><div class="feature-row"><div class="feature-icon">🛡️</div><div><strong>Güvenli başlangıç</strong><small>İlk sürümde kimlik, diploma veya sertifika yüklemen gerekmiyor.</small></div></div></div>`;
 screen.innerHTML=layout(x); window.scrollTo({top:0,behavior:'smooth'});
}
function jobCard(j){return `<article class="job"><div class="job-top"><div class="company-logo">Y</div><div><h3>${j.title}</h3><div class="company">${j.company}</div></div></div><div class="meta"><span class="pill">📍 ${j.city}</span><span class="pill">⏱ ${j.type}</span><span class="pill">${j.tag}</span></div><button class="apply" onclick="toast('Bu ilk sürümde başvuru bağlantısını daha sonra resmi işveren sayfasına bağlayacağız.')">İlanı incele →</button></article>`}
function filterJobs(q){const el=document.getElementById('joblist'); if(!el)return; const v=q.toLowerCase().trim(); const list=jobs.filter(j=>`${j.title} ${j.company} ${j.city} ${j.type} ${j.tag}`.toLowerCase().includes(v)); el.innerHTML=list.map(jobCard).join('')||'<div class="empty">Şimdilik sonuç bulunamadı.</div>'}
function demoTranslate(){const input=document.getElementById('translateInput'); const result=document.getElementById('translateResult'); if(!input.value.trim()){toast('Önce bir cümle yaz.');return} result.innerHTML=`<div class="result"><small style="color:#91a4bd">Örnek sonuç</small><p style="font-size:18px;margin:8px 0 0"><strong>“${escapeHtml(input.value)}”</strong></p><p class="sub" style="margin:6px 0 0">Gerçek çeviri motoru bir sonraki geliştirmede bağlanacak.</p></div>`}
function clearTranslate(){const input=document.getElementById('translateInput'); if(input)input.value=''; const result=document.getElementById('translateResult'); if(result)result.innerHTML=''}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toggleMenu(){const d=document.getElementById('drawer'),s=document.getElementById('shade'); d.classList.toggle('open');s.classList.toggle('open');d.setAttribute('aria-hidden',!d.classList.contains('open'))}
function toast(msg){const old=document.querySelector('.toast'); if(old)old.remove(); const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
show('home');
